[build]
  command = "prisma generate && next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**", "node_modules/@prisma/client/**"]

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200
  conditions = {Role = ["admin", "seller", "buyer"]}