[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Suporte a Next.js na Netlify (runtime)
[[plugins]]
  package = "@netlify/plugin-nextjs"
